name: Cross-Platform Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            artifact-name: todo-macos-x86_64

          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            artifact-name: todo-macos-aarch64

          - os-name: Linux-aarch64-gnu
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
            artifact-name: todo-linux-aarch64

          - os-name: Linux-i686-gnu
            runs-on: ubuntu-24.04
            target: i686-unknown-linux-gnu
            artifact-name: todo-linux-i686

          - os-name: Linux-x86_64-gnu
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            artifact-name: todo-linux-x86_64

          - os-name: Windows-i686-msvc
            runs-on: windows-latest
            target: i686-pc-windows-msvc
            artifact-name: todo-windows-i686.exe

          - os-name: Windows-x86_64-gnu
            runs-on: windows-latest
            target: x86_64-pc-windows-gnu
            artifact-name: todo-windows-x86_64-gnu.exe

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            artifact-name: todo-windows-x86_64.exe

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch_depth: 0
      
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact-name }}
          path: target/${{ matrix.platform.target }}/release/todo${{ matrix.platform.target == 'i686-pc-windows-msvc' || matrix.platform.target == 'x86_64-pc-windows-gnu' || matrix.platform.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        with:
          tag: ${{ github.ref_name }}
          output: CHANGELOG.md
          config: .github/git-cliff.toml

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Version ${{ github.ref_name }}"
          body_path: CHANGELOG.md
          files: |
            artifacts/*
            CHANGELOG.md
            LICENSE  # Optional: Include license
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
